export const book = {
    D1: {
        type: "deletion",

        1: {
            a: { original: "birthday", omit: "birth", solution: "day" },
            b: { original: "daytime", omit: "day", solution: "time" },
            c: { original: "airport", omit: "air", solution: "port" },
            d: { original: "eyesight", omit: "eye", solution: "sight" },
            e: { original: "football", omit: "foot", solution: "ball" },
            f: { original: "diskdrive", omit: "disk", solution: "drive" },
            g: { original: "bedtime", omit: "bed", solution: "time" },
            h: { original: "iceberg", omit: "ice", solution: "berg" },
            i: { original: "flashlight", omit: "flash", solution: "light" },
            j: { original: "doorbell", omit: "door", solution: "bell" },
        },

        2: {
            a: { original: "keyboard", omit: "key", solution: "board" },
            b: { original: "haystack", omit: "hay", solution: "stack" },
            c: { original: "greyhound", omit: "grey", solution: "hound" },
            d: { original: "clockwise", omit: "clock", solution: "wise" },
            e: { original: "halfway", omit: "half", solution: "way" },
            f: { original: "grandson", omit: "grand", solution: "son" },
            g: { original: "bookcase", omit: "book", solution: "case" },
            h: { original: "postmark", omit: "post", solution: "mark" },
            i: { original: "racetrack", omit: "race", solution: "track" },
            j: { original: "sandbox", omit: "sand", solution: "box" },
        },

        3: {
            a: { original: "goldfish", omit: "gold", solution: "fish" },
            b: { original: "blackboard", omit: "black", solution: "board" },
            c: { original: "headlight", omit: "head", solution: "light" },
            d: { original: "gumdrop", omit: "gum", solution: "drop" },
            e: { original: "baseball", omit: "base", solution: "ball" },
            f: { original: "downtown", omit: "down", solution: "town" },
            g: { original: "mailbox", omit: "mail", solution: "box" },
            h: { original: "cartwheel", omit: "cart", solution: "wheel" },
            i: { original: "haircut", omit: "hair", solution: "cut" },
            j: { original: "footprint", omit: "foot", solution: "print" },
        },

        4: {
            a: { original: "sunset", omit: "sun", solution: "set" },
            b: { original: "lifeguard", omit: "guard", solution: "life" },
            c: { original: "doorstep", omit: "door", solution: "step" },
            d: { original: "railroad", omit: "road", solution: "rail" },
            e: { original: "freeway", omit: "free", solution: "way" },
            f: { original: "seashell", omit: "shell", solution: "sea" },
            g: { original: "rowboat", omit: "row", solution: "boat" },
            h: { original: "drawbridge", omit: "bridge", solution: "draw" },
            i: { original: "himself", omit: "him", solution: "self" },
            j: { original: "income", omit: "come", solution: "in" },
        },

        5: {
            a: { original: "tadpole", omit: "tad", solution: "pole" },
            b: { original: "moonlight", omit: "light", solution: "moon" },
            c: { original: "sidewalk", omit: "side", solution: "walk" },
            d: { original: "grassland", omit: "land", solution: "grass" },
            e: { original: "textbook", omit: "text", solution: "book" },
            f: { original: "something", omit: "thing", solution: "some" },
            g: { original: "leapfrog", omit: "leap", solution: "frog" },
            h: { original: "therefore", omit: "fore", solution: "there" },
            i: { original: "sawhorse", omit: "saw", solution: "horse" },
            j: { original: "grandstand", omit: "stand", solution: "grand" },
        },

        6: {
            a: { original: "jigsaw", omit: "jig", solution: "saw" },
            b: { original: "sandwich", omit: "wich", solution: "sand" },
            c: { original: "tightrope", omit: "tight", solution: "rope" },
            d: { original: "doorway", omit: "way", solution: "door" },
            e: { original: "softball", omit: "soft", solution: "ball" },
            f: { original: "forehead", omit: "head", solution: "fore" },
            g: { original: "passport", omit: "pass", solution: "port" },
            h: { original: "homeland", omit: "land", solution: "home" },
            i: { original: "indoors", omit: "in", solution: "doors" },
            j: { original: "hilltop", omit: "top", solution: "hill" },
        },

        7: {
            a: { original: "grapefruit", omit: "grape", solution: "fruit" },
            b: { original: "outside", omit: "side", solution: "out" },
            c: { original: "midnight", omit: "mid", solution: "night" },
            d: { original: "billboard", omit: "board", solution: "bill" },
            e: { original: "outlook", omit: "out", solution: "look" },
            f: { original: "aircraft", omit: "air", solution: "craft" },
            g: { original: "hillside", omit: "side", solution: "hill" },
            h: { original: "icebox", omit: "ice", solution: "box" },
            i: { original: "sideways", omit: "ways", solution: "side" },
        },

        8: {
            a: { original: "spacecraft", omit: "space", solution: "craft" },
            b: { original: "background", omit: "ground", solution: "back" },
            c: { original: "playpen", omit: "play", solution: "pen" },
            d: { original: "outgrow", omit: "grow", solution: "out" },
            e: { original: "payroll", omit: "pay", solution: "roll" },
            f: { original: "handball", omit: "ball", solution: "hand" },
            g: { original: "necktie", omit: "neck", solution: "tie" },
            h: { original: "bulldog", omit: "dog", solution: "bull" },
            i: { original: "skyline", omit: "sky", solution: "line" },
            j: { original: "landslide", omit: "slide", solution: "land" },
        }
    },

    G1: {
        type: "substitution",

        1: {
            a: { original: "wood", omit: "w", replace: "g", solution: "good" },
            b: { original: "fed", omit: "f", replace: "r", solution: "red" },
            c: { original: "sun", omit: "s", replace: "f", solution: "fun" },
            d: { original: "tab", omit: "t", replace: "c", solution: "cab" },
            e: { original: "load", omit: "l", replace: "r", solution: "road" },
            f: { original: "lime", omit: "l", replace: "d", solution: "dime" },
            g: { original: "rain", omit: "r", replace: "ch", solution: "chain" },
            h: { original: "came", omit: "c", replace: "g", solution: "game" },
            i: { original: "box", omit: "b", replace: "f", solution: "fox" },
            j: { original: "mix", omit: "m", replace: "s", solution: "six" },
        },

        2: {
            a: { original: "bad", omit: "b", replace: "h", solution: "had" },
            b: { original: "men", omit: "m", replace: "t", solution: "ten" },
            c: { original: "sheep", omit: "sh", replace: "k", solution: "keep" },
            d: { original: "cow", omit: "c", replace: "h", solution: "how" },
            e: { original: "bake", omit: "b", replace: "l", solution: "lake" },
            f: { original: "joke", omit: "j", replace: "w", solution: "woke" },
            g: { original: "keep", omit: "k", replace: "l", solution: "leap" },
            h: { original: "meet", omit: "m", replace: "w", solution: "wheat" },
            i: { original: "cut", omit: "c", replace: "w", solution: "what" },
            j: { original: "niece", omit: "n", replace: "p", solution: "piece" },
        },

        3: {
            a: { original: "moan", omit: "m", replace: "c", solution: "cone" },
            b: { original: "cane", omit: "c", replace: "r", solution: "rain" },
            c: { original: "bad", omit: "b", replace: "m", solution: "mad" },
            d: { original: "look", omit: "l", replace: "b", solution: "book" },
            e: { original: "care", omit: "c", replace: "f", solution: "fair" },
            f: { original: "kneel", omit: "n", replace: "w", solution: "wheel" },
            g: { original: "south", omit: "s", replace: "m", solution: "mouth" },
            h: { original: "sad", omit: "s", replace: "h", solution: "had" },
            i: { original: "fell", omit: "f", replace: "b", solution: "bell" },
            j: { original: "dig", omit: "d", replace: "w", solution: "wig" },
        },

        4: {
            a: { original: "night", omit: "n", replace: "b", solution: "bite" },
            b: { original: "house", omit: "h", replace: "m", solution: "mouse" },
            c: { original: "hub", omit: "h", replace: "c", solution: "cub" },
            d: { original: "hot", omit: "h", replace: "l", solution: "lot" },
            e: { original: "hose", omit: "h", replace: "n", solution: "nose" },
            f: { original: "six", omit: "s", replace: "f", solution: "fix" },
            g: { original: "hum", omit: "h", replace: "s", solution: "sum" },
            h: { original: "dime", omit: "d", replace: "r", solution: "rhyme" },
            i: { original: "made", omit: "m", replace: "sh", solution: "shade" },
            j: { original: "call", omit: "c", replace: "b", solution: "ball" },
        },

        5: {
            a: { original: "pool", omit: "p", replace: "t", solution: "tool" },
            b: { original: "hug", omit: "h", replace: "t", solution: "tug" },
            c: { original: "ride", omit: "r", replace: "g", solution: "guide" },
            d: { original: "sing", omit: "s", replace: "th", solution: "thing" },
            e: { original: "chill", omit: "ch", replace: "f", solution: "fill" },
            f: { original: "wedge", omit: "w", replace: "h", solution: "hedge" },
            g: { original: "soup", omit: "s", replace: "h", solution: "hoop" },
            h: { original: "bell", omit: "b", replace: "f", solution: "fell" },
            i: { original: "base", omit: "b", replace: "f", solution: "face" },
            j: { original: "peel", omit: "p", replace: "m", solution: "meal" },
        },

        6: {
            a: { original: "real", omit: "r", replace: "s", solution: "seal" },
            b: { original: "bowl", omit: "b", replace: "g", solution: "goal" },
            c: { original: "pick", omit: "p", replace: "k", solution: "kick" },
            d: { original: "feel", omit: "f", replace: "r", solution: "reel" },
            e: { original: "mail", omit: "m", replace: "n", solution: "nail" },
            f: { original: "mood", omit: "m", replace: "f", solution: "food" },
            g: { original: "mouse", omit: "m", replace: "h", solution: "house" },
            h: { original: "hush", omit: "h", replace: "r", solution: "rush" },
            i: { original: "bid", omit: "b", replace: "h", solution: "hid" },
            j: { original: "beach", omit: "b", replace: "p", solution: "peach" },
        },

        7: {
            a: { original: "knife", omit: "n", replace: "w", solution: "wife" },
            b: { original: "hid", omit: "h", replace: "k", solution: "kid" },
            c: { original: "cool", omit: "c", replace: "p", solution: "pool" },
            d: { original: "fan", omit: "f", replace: "r", solution: "ran" },
            e: { original: "net", omit: "n", replace: "s", solution: "set" },
            f: { original: "guess", omit: "g", replace: "y", solution: "yes" },
            g: { original: "ball", omit: "b", replace: "t", solution: "tall" },
            h: { original: "rid", omit: "r", replace: "d", solution: "did" },
            i: { original: "tax", omit: "t", replace: "w", solution: "wax" },
            j: { original: "bought", omit: "b", replace: "c", solution: "caught" },
        }
    }
}